# This workflow builds and publishes the NuGet package when a new tag is pushed.
name: Publish NuGet Package

on:
  push:
    branches:
      - main # Only run on pushes to the main branch
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger on exact tags like v1.0.0, v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Get version from tag
      id: get_version
      # This step extracts the version number from the tag (e.g., v1.1.0 -> 1.1.0)
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{ steps.get_version.outputs.VERSION }} -o ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"