name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  #-------------------------
  # Job 1: Build the Project
  #-------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore, Build, and Pack
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet pack --configuration Release --no-build -p:PackageVersion=${GITHUB_REF_NAME#v} -o ./artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

  #-----------------------------
  # Job 2: Publish to NuGet.org
  #-----------------------------
  publish-nuget:
    runs-on: ubuntu-latest
    needs: build # <-- This job depends on the 'build' job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"

  #-----------------------------------
  # Job 3: Create a GitHub Release
  #-----------------------------------
  create-github-release:
    runs-on: ubuntu-latest
    needs: publish-nuget # <-- This job depends on the 'publish-nuget' job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "*.nupkg"